In [2]:
import argparse as ap
import numpy as np
## using command: pip install opencv-python
## may use this code to install module 'skbuild': pip install scikit-build
import cv2
import pandas as pd


    
    
#把热图抠出来
path = "/home/lifs/temp/cor/"
row = 7
columns = 6
output = "/home/lifs/temp/cor/"

hotmap = cv2.imread(path + "correlationPlot.png")
hsv = cv2.cvtColor(hotmap,cv2.COLOR_BGR2HSV)
minval = np.array([1,0,46])
maxval = np.array([124,255,255])
mask = cv2.inRange(hsv,minval,maxval)
color = cv2.bitwise_and(hotmap,hotmap,mask=mask)

#扣出区块
color[color==0]=255
gray = cv2.cvtColor(color,cv2.COLOR_BGR2GRAY)
gray[:,int(gray.shape[1]*0.9):]=255
ret,binary = cv2.threshold(gray,254,255,cv2.THRESH_BINARY)
contours, hierarchy = cv2.findContours(binary,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
img = cv2.drawContours(hotmap.copy(), contours, -1, (0,255,0), 1)

#按序号取出不同方块
inf = []
for i in range(len(contours)):
    x,y,w,h = cv2.boundingRect(contours[i])
    inf.append([x,y,w,h])
inf.sort(key=lambda x:x[1])
inf.sort(key=lambda y:y[0])
inf.pop(0)
r = [i for i in range(1,row+1)]*columns
c = [[j]*row for j in range(1,columns+1)]
c = [j for m in c for j in m]
info = np.array(inf)

    ##保存数据
df = pd.DataFrame(info,columns=['x','y','w','h'])
    #df['row'] = r
    #df['columns'] = c
    #df.to_csv(output+'splitWinArgs.csv')

In [2]:
df['x+w'] = df['x'] + df['w'] 
df['y+h'] = df['y'] + df['h'] 
df_x = df.drop_duplicates('x')

x_gap = np.array(df_x['x'][1:])-np.array(df_x['x+w'][:-1])

In [17]:
x_realgap = 2
y_realgap = 2
if (not len(x_gap[x_gap == 2])) or len(x_gap[x_gap == 2]) != columns-1:
    mask = np.unique(x_gap)
    tmp = np.empty(len(mask), dtype=int)
    for v,j in enumerate(mask):
        tmp[v] = np.sum(x_gap==j)
    x_realgap = max(mask[tmp == columns-1]) #col
else:

In [3]:
x_gap

array([ 2, -1,  2, -1,  2, -1])

In [4]:
df_x

      x   y    w   h  x+w  y+h
0    54  54  104  16  158   70
4   160  54   20  16  180   70
8   179  54   95  16  274   70
12  276  54   44  16  320   70
16  319  54  140  16  459   70
20  461  54   12  16  473   70
24  472  54  109  16  581   70

In [3]:
df

      x    y    w    h
0    54   54   59   34
1    54   90   59   85
2    54  177   59   28
3    54  207   59  198
4    54  407   59   74
5    54  483   59   10
6    54  495   59  139
7   115   54  106   34
8   115   90  106   85
9   115  177  106   28
10  115  207  106  198
11  115  407  106   74
12  115  483  106   10
13  115  495  106  139
14  223   54  133   34
15  223   90  133   85
16  223  177  133   28
17  223  207  133  198
18  223  407  133   74
19  223  483  133   10
20  223  495  133  139
21  358   54  111   34
22  358   90  111   85
23  358  177  111   28
24  358  207  111  198
25  358  407  111   74
26  358  483  111   10
27  358  495  111  139
28  471   54   24   34
29  471   90   24   85
30  471  177   24   28
31  471  207   24  198
32  471  407   24   74
33  471  483   24   10
34  471  495   24  139
35  497   54   64   34
36  497   90   64   85
37  497  177   64   28
38  497  207   64  198
39  497  407   64   74
40  497  483   64   10
41  497  495   64  139